### ISSUE TITLE
Windows support would be great

### ISSUE THREAD

**Issue by heini** [solarkennedy/puppet-btsync#1]
As the subject says...

We're using Puppet on Windows and are currently evaluating BTSync. Would be great if we could install and configure it to our Windows agents via Puppet.

**Comment by solarkennedy** [comment]
Cool! Unfortunately I have 0 experience with Puppet on Windows (or Windows in general). 

Does the BTSync app on windows support being configured via a config file? And how do you deploy the app efficiently? So many questions. 

I'm up for pull requests and further exploration.

**Comment by solarkennedy** [comment]
Any update on this, or should I close? 

In theory puppet has the providers to install btsync on windows, and possibly manage its service? I don't know about config though. In theory the config file is somewhere.

**Comment by heini** [comment]
Am Dienstag 18 Februar 2014, 04:44:14 schrieb Kyle Anderson:

> Any update on this, or should I close?

No update.

> In theory puppet has the providers to install btsync on windows, and
> possibly manage its service? I don't know about config though. In theory
> the config file is somewhere.

But in real life BTsync still can't be installed unattended on Windows, has no 
service and configuration is a binary blob :(.
