### ISSUE TITLE
x86_64 <> amd64 in filename of the program binary

### ISSUE THREAD

**Issue by hansbogert** [solarkennedy/puppet-btsync#2]
The download script downloads using the name 'btsync.x86_64', the install script looks for 'btsync.amd64'

**Comment by solarkennedy** [comment]
Fixed for now.

`$::architecture` seems to be either amd64 or x86_64 depending on distro.

`$::hardwareisa` is `uname -p`, which is probably what I want.

However, it is probably going to break ARM systems, but the number of people running Puppet on arm is pretty small. (probably just me)
